name: blutooth_print_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bluetooth_print: ^4.3.0
  pdf: ^3.5.1
  pdfx: ^2.7.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
  fonts:
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
    - family: Tajwal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: Schyler
      fonts:
        - asset: assets/fonts/hacen_tunisia.ttf
